org.gradle.jvmargs=-Xmx4G
android.useAndroidX=true
android.enableJetifier=true
android.defaults.buildfeatures.buildconfig=true
android.nonTransitiveRClass=false
android.nonFinalResIds=false
android.bundle.enableUncompressedNativeLibs=true
# Avoid Kotlin incremental cache errors when project (E:) and pub cache (C:) are on different drives.
kotlin.incremental=false